# =========== Copyright 2023 @ CAMEL-AI.org. All Rights Reserved. ===========
# Licensed under the Apache License, Version 2.0 (the “License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an “AS IS” BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =========== Copyright 2023 @ CAMEL-AI.org. All Rights Reserved. ===========
from dataclasses import dataclass
from typing import Any, Dict

from oasis.social_platform.typing import ActionType


@dataclass
class ManualAction:
    r"""Some manual predefined social platform actions that need to be
    executed by certain agents.

    Args:
        agent_id: The ID of the agent that will perform the action.
        action: The action to perform.
        args: The arguments to pass to the action. For details of each args in
            each action, please refer to
            `https://github.com/camel-ai/oasis/blob/main/oasis/social_agent/agent_action.py`.
    """
    action_type: ActionType
    action_args: Dict[str, Any]

    def init(self, action_type, action_args):
        self.action_type = action_type
        self.action_args = action_args


@dataclass
class LLMAction:
    r"""Represents actions generated by a Language Learning Model (LLM)."""

    def init(self):
        pass

@dataclass
class HeuristicAction:
    """
    一个标记动作 (marker action)，用于 OasisEnv。
    
    当 env.step() 收到一个 agent 对应的是 HeuristicAction 实例时,
    它会跳过 LLM 和 ManualAction 的逻辑, 转而直接
    `await agent.step()`。
    
    这允许 HeuristicAgent/ABMAgent (如 LurkerAgent) 的
    `step()` 逻辑被集成到统一的 env.step() 工作流中。
    """
    def __init__(self):
        # 这个类不需要任何参数, 它只是一个类型标记
        pass